apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crds
  - namespaces.yaml
  - demo-configmap.yaml
  - addons/cert-manager/application.yaml
  - addons/envoy-gateway/application.yaml
  - gateway



