apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - applicationset.yaml
  - crds
  - namespaces.yaml
  - demo-configmap.yaml
  - cert-manager/clusterissuer-selfsigned.yaml
  - gateway



