apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/rayabueg/gitops-lab.git
    targetRevision: main
    path: clusters/k8s-lab/addons/core-dns
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - Replace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 15
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
